name: basic-steps

on:
  workflow_call:

jobs:

  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew check jacocoTestReport

      - name: Upload JaCoCo coverage data
        uses: actions/upload-artifact@master
        with:
          name: tests-artifacts
          path: |
            */build/jacoco
            */build/test-results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
