# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build & Test
      run: ./gradlew check --parallel

    - name: Add test results to PR
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "*/build/test-results/**/*.xml"

    - name: Run diff coverage check
      run: ./gradlew diffCoverage -PdiffBase="refs/remotes/origin/$GITHUB_BASE_REF"

    - name: Add diff coverage report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      if: always()
      continue-on-error: true
      with:
        paths: build/reports/jacoco/diffCoverage/report.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create full coverage report
      run: ./gradlew jacocoRootReport
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
